on: 
 push:
   branches: 
     -master
jobs:
  my_testing:
     runs-on: ubuntu-latest

     steps:
      - name: Print Hello Messege
        run: echo "Hello from test"

  my_deploy:
     runs-on: ubuntu-latest

     steps:
      - name: Print Hello Messege
        run: echo "Hello from deploy"
